package log

//	issuing_holder.Log object
//	Every time an IssuingHolder entity is updated, a corresponding issuing_holder.Log
//	is generated for the entity. This log is never generated by the
//	user, but it can be retrieved to check additional information
//	on the IssuingHolder.
//
//	Attributes:
//	- id [string]: unique id returned when the log is created. ex: "5656565656565656"
//	- holder [IssuingHolder]: IssuingHolder entity to which the log refers to.
//	- type [string]: type of the IssuingHolder event which triggered the log creation. ex: "blocked", "canceled", "created", "unblocked", "updated"
//	- created [datetime.datetime]: creation datetime for the log. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)

type Log struct {
	Id      string        `json:"id"`
	Holder  IssuingHolder `json:"holder"`
	Type    string        `json:"type"`
	Created string        `json:"created"`
}

var resource = map[string]string{"class": Log{}, "name": "IssuingHolderLog"}

func Get() {
	//	Retrieve a specific issuing_holder.Log
	//	Receive a single issuing_holder.Log object previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: object unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- issuing_holder.Log object with updated attributes

}

func Query() {
	//	Retrieve issuing_holder.Log
	//	Receive a generator of issuing_holder.Log objects previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//	- limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
	//	- ids [list of strings, default None]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
	//	- after [datetime.date or string, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
	//	- before [datetime.date or string, default None] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
	//	- types [list of strings, default None]: filter for log event types. ex: ["created", "blocked"]
	//	- holder_ids [list of strings, default None]: list of IssuingHolder ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- generator of issuing_holder.Log objects with updated attributes

}

func Page() {
	//	Retrieve paged issuing_holder.Log
	//	Receive a list of up to 100 issuing_holder.Log objects previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//	- cursor [string, default None]: cursor returned on the previous page function call
	//	- ids [list of strings, default None]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
	//	- limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
	//	- after [datetime.date or string, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
	//	- before [datetime.date or string, default None] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
	//	- types [list of strings, default None]: filter for log event types. ex: ["created", "blocked"]
	//	- holder_ids [list of strings, default None]: list of IssuingHolder ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- list of issuing_holder.Log objects with updated attributes
	//	- cursor to retrieve the next page of issuing_holder.Log objects
}
