package log

import (
	"encoding/json"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	PixFraud "github.com/starkinfra/sdk-go/starkinfra/pixfraud"
	"github.com/starkinfra/sdk-go/starkinfra/utils"
	"time"
)

//	PixFraud.Log struct
//
//	Every time a PixFraud entity is modified, a corresponding PixFraud.Log
//	is generated for the entity. This log is never generated by the user.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Fraud [PixFraud struct]: PixFraud entity to which the log refers to.
//	- Type [string]: Type of the PixFraud event which triggered the log creation. ex: "canceled", "canceling", "created", "failed", "registered"
//	- Errors [slice of strings]: Slice of errors linked to this PixFraud event
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id      string            `json:",omitempty"`
	Fraud   PixFraud.PixFraud `json:",omitempty"`
	Type    string            `json:",omitempty"`
	Errors  []string          `json:",omitempty"`
	Created *time.Time        `json:",omitempty"`
}

var resource = map[string]string{"name": "PixFraudLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific PixFraud.Log by its id
	//
	//	Receive a single PixFraud.Log struct previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- pixFraud.Log struct that corresponds to the given id.
	var pixFraudLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &pixFraudLog)
	if unmarshalError != nil {
		return pixFraudLog, err
	}
	return pixFraudLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve PixFraud.Log structs
	//
	//	Receive a channel of PixFraud.Log structs previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by types. Options: []string{"canceled", "canceling", "created", "failed", "registered"}
	//		- fraudIds [slice of strings, default nil]: Slice of PixFraud ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- ids [slice of strings, default nil]: Slice of ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- channel of PixFraud.Log structs with updated attributes
	var pixFraudLog Log
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &pixFraudLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- pixFraudLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logs)
		close(logsError)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged PixFraud.Log structs
	//
	//	Receive a slice of up to 100 PixFraud.Log structs previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. Max = 100. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by types. Options: []string{"canceled", "canceling", "created", "failed", "registered"}
	//		- fraudIds [slice of strings, default nil]: Slice of PixFraud ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- ids [slice of strings, default nil]: Slice of ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- slice of PixFraud.Log structs with updated attributes
	//	- cursor to retrieve the next page of PixFraud.Log structs
	var pixFraudLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &pixFraudLogs)
	if unmarshalError != nil {
		return pixFraudLogs, cursor, err
	}
	return pixFraudLogs, cursor, err
}
