package log

import (
	"encoding/json"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	IssuingToken "github.com/starkinfra/sdk-go/starkinfra/issuingtoken"
	"github.com/starkinfra/sdk-go/starkinfra/utils"
	"time"
)

//	IssuingToken.Log struct
//
//	Every time an IssuingToken entity is modified, a corresponding IssuingToken.Log
//	is generated for the entity. This log is never generated by the
//	user, but it can be retrieved to check additional information
//	on the IssuingToken.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Token [IssuingToken struct]: IssuingToken entity to which the log refers to.
//	- Errors [slice of strings]: Slice of errors linked to this IssuingToken event.
//	- Type [string]: Type of the IssuingToken event which triggered the log creation. ex: "blocked", "blocking", "canceled", "canceling", "created", "denied", "failed", "frozen", "unblocked", "unblocking", "unfrozen", "updated".
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id      string                    `json:",omitempty"`
	Token   IssuingToken.IssuingToken `json:",omitempty"`
	Errors  []string                  `json:",omitempty"`
	Type    string                    `json:",omitempty"`
	Created *time.Time                `json:",omitempty"`
}

var resource = map[string]string{"name": "IssuingTokenLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific IssuingToken.Log
	//
	//	Receive a single IssuingToken.Log struct previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- issuingToken.Log struct with updated attributes
	var issuingTokenLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &issuingTokenLog)
	if unmarshalError != nil {
		return issuingTokenLog, err
	}
	return issuingTokenLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve IssuingToken.Log
	//
	//	Receive a channel of IssuingToken.Log structs previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- ids [slice of strings, default nil]: Slice of ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- tokenIds [slice of strings, default nil]: Slice of IssuingToken ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date.  ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"blocked", "blocking", "canceled", "canceling", "created", "denied", "failed", "frozen", "unblocked", "unblocking", "unfrozen", "updated"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- channel of IssuingToken.Log structs with updated attributes
	var issuingTokenLog Log
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &issuingTokenLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- issuingTokenLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logs)
		close(logsError)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged IssuingToken.Log
	//
	//	Receive a slice of up to 100 IssuingToken.Log structs previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- ids [slice of strings, default nil]: Slice of ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- tokenIds [slice of strings, default nil]: Slice of IssuingToken ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. Max = 100. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date.  ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"blocked", "blocking", "canceled", "canceling", "created", "denied", "failed", "frozen", "unblocked", "unblocking", "unfrozen", "updated"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- slice of IssuingToken.Log structs with updated attributes
	//	- cursor to retrieve the next page of IssuingToken.Log structs
	var issuingTokenLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &issuingTokenLogs)
	if unmarshalError != nil {
		return issuingTokenLogs, cursor, err
	}
	return issuingTokenLogs, cursor, err
}
