package issuingcard

//	IssuingCard object
//	The IssuingCard object displays the information of the cards created in your Workspace.
//	Sensitive information will only be returned when the "expand" parameter is used, to avoid security concerns.
//
//	Parameters (required):
//	- holder_name [string]: card holder name. ex: "Tony Stark"
//	- holder_tax_id [string]: card holder tax ID. ex: "012.345.678-90"
//	- holder_external_id [string]: card holder unique id, generated by the user to avoid duplicated holders. ex: "my-entity/123"
//
//	Parameters (optional):
//	- display_name [string, default None]: card displayed name. ex: "ANTHONY STARK"
//	- rules [list of IssuingRule, default []]: [EXPANDABLE] list of card spending rules.
//	- bin_id [string, default None]: BIN ID to which the card is bound. ex: "53810200"
//	- tags [list of strings, default None]: list of strings for tagging. ex: ["travel", "food"]
//	- street_line_1 [string, default sub-issuer street line 1]: card holder main address. ex: "Av. Paulista, 200"
//	- street_line_2 [string, default sub-issuer street line 2]: card holder address complement. ex: "Apto. 123"
//	- district [string, default sub-issuer district]: card holder address district / neighbourhood. ex: "Bela Vista"
//	- city [string, default sub-issuer city]: card holder address city. ex: "Rio de Janeiro"
//	- state_code [string, default sub-issuer state code]: card holder address state. ex: "GO"
//	- zip_code [string, default sub-issuer zip code]: card holder address zip code. ex: "01311-200"
//
//	Attributes (return-only):
//	- id [string]: unique id returned when IssuingCard is created. ex: "5656565656565656"
//	- holder_id [string]: card holder unique id. ex: "5656565656565656"
//	- type [string]: card type. ex: "virtual"
//	- status [string]: current IssuingCard status. ex: "active", "blocked", "canceled", "expired".
//	- number [string]: [EXPANDABLE] masked card number. Expand to unmask the value. ex: "123".
//	- security_code [string]: [EXPANDABLE] masked card verification value (cvv). Expand to unmask the value. ex: "123".
//	- expiration [datetime.datetime]: [EXPANDABLE] masked card expiration datetime. Expand to unmask the value. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0).
//	- updated [datetime.datetime]: latest update datetime for the IssuingCard. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
//	- created [datetime.datetime]: creation datetime for the IssuingCard. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)

type IssuingCard struct {
	HolderName       string
	HolderTaxId      string
	HolderExternalId string
	DisplayName      string
	Rules            []IssuingRules
	BinId            string
	Tags             []string
	StreetLine1      string
	StreetLine2      string
	District         string
	City             string
	StateCode        string
	ZipCode          string
	Id               string
	HolderId         string
	Type             string
	Status           string
	Number           string
	SecurityCode     string
	Expiration       string
	Updated          string
	Created          string
}

var resource = map[string]string{"class": IssuingCard{}, "name": "IssuingCard"}

func Create() {
	//	Create IssuingCards
	//	Send a list of IssuingCard objects for creation at the Stark Infra API
	//
	//	Parameters (required):
	//	- cards [list of IssuingCard objects]: list of IssuingCard objects to be created in the API
	//
	//	Parameters (optional):
	//	- expand [list of strings, default []]: fields to expand information. ex: ["rules", "security_code", "number", "expiration"]
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- list of IssuingCard objects with updated attributes

}

func Get() {
	//	Retrieve a specific IssuingCards
	//	Receive a single IssuingCards object previously created in the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: object unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- expand [list of strings, default None]: fields to expand information. ex: ["rules", "security_code", "number", "expiration"]
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- IssuingCards object with updated attributes

}

func Query() {
	//	Retrieve IssuingCards
	//	Receive a generator of IssuingCards objects previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//	- limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
	//	- ids [list of strings, default None]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
	//	- after [datetime.date or string, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
	//	- before [datetime.date or string, default None] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
	//	- status [list of strings, default None]: filter for status of retrieved objects. ex: ["active", "blocked", "canceled", "expired"]
	//	- types [list of strings, default None]: card type. ex: ["virtual"]
	//	- holder_ids [list of strings]: card holder IDs. ex: ["5656565656565656", "4545454545454545"]
	//	- tags [list of strings, default None]: tags to filter retrieved objects. ex: ["tony", "stark"]
	//	- expand [list of strings, default []]: fields to expand information. ex: ["rules", "security_code", "number", "expiration"]
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- generator of IssuingCards objects with updated attributes

}

func Page() {
	//	Retrieve paged IssuingCards
	//	Receive a list of IssuingCards objects previously created in the Stark Infra API and the cursor to the next page.
	//
	//	Parameters (optional):
	//	- cursor [string, default None]: cursor returned on the previous page function call
	//	- limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
	//	- ids [list of strings, default None]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
	//	- after [datetime.date or string, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
	//	- before [datetime.date or string, default None] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
	//	- status [list of strings, default None]: filter for status of retrieved objects. ex: ["active", "blocked", "canceled", "expired"]
	//	- types [list of strings, default None]: card type. ex: ["virtual"]
	//	- holder_ids [list of strings]: card holder IDs. ex: ["5656565656565656", "4545454545454545"]
	//	- tags [list of strings, default None]: tags to filter retrieved objects. ex: ["tony", "stark"]
	//	- expand [list of strings, default []]: fields to expand information. ex: ["rules", "security_code", "number", "expiration"]
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- list of IssuingCards objects with updated attributes
	//	- cursor to retrieve the next page of IssuingCards objects
}

func Update() {
	//	Update IssuingCard entity
	//	Update an IssuingCard by passing id.
	//
	//	Parameters (required):
	//	- id [string]: IssuingCard id. ex: '5656565656565656'
	//
	//	Parameters (optional):
	//	- status [string, default None]: You may block the IssuingCard by passing 'blocked' or activate by passing 'active' in the status
	//	- display_name [string, default None]: card displayed name
	//	- rules [list of dictionaries, default None]: list of dictionaries with "amount": int, "currencyCode": string, "id": string, "interval": string, "name": string pairs.
	//	- tags [list of strings]: list of strings for tagging
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- target IssuingCard with updated attributes
}

func Cancel() {
	//	Cancel an IssuingCard entity
	//	Cancel an IssuingCard entity previously created in the Stark Infra API
	//
	//	Parameters (required):
	//	- id [string]: IssuingCard unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- canceled IssuingCard object

}
