package log

//	PixKey.Log object
//	Every time a PixKey entity is modified, a corresponding PixKey.Log
//	is generated for the entity. This log is never generated by the user.
//
//	Attributes:
//	- id [string]: unique id returned when the log is created. ex: "5656565656565656"
//	- key [PixKey]: PixKey entity to which the log refers to.
//	- type [string]: type of the PixKey event which triggered the log creation. ex: "created", "registered", "updated", "failed", "canceling", "canceled".
//	- errors [list of strings]: list of errors linked to this PixKey event
//	- created [datetime.datetime]: creation datetime for the log. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)

type Log struct {
	Id      string   `json:"id"`
	Key     PixKey   `json:"key"`
	Type    string   `json:"type"`
	Errors  []string `json:"errors"`
	Created string   `json:"created"`
}

var resource = map[string]string{"class": Log{}, "name": "PixKeyLog"}

func Get() {
	//	Retrieve a specific PixKey.Log
	//	Receive a single PixKey.Log object previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: object unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- PixKey.Log object with updated attributes
}

func Query() {
	//	Retrieve PixKey.Logs
	//	Receive a generator of PixKey.Log objects previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//	- ids [list of strings, default None]: Log ids to filter PixKey Logs. ex: ["5656565656565656"]
	//	- limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
	//	- after [datetime.date or string, default None]: date filter for objects created after specified date. ex: datetime.date(2020, 3, 10)
	//	- before [datetime.date or string, default None]: date filter for objects created before a specified date. ex: datetime.date(2020, 3, 10)
	//	- types [list of strings, default None]: filter retrieved objects by types. ex: ["created", "registered", "updated", "failed", "canceling", "canceled"]
	//	- key_ids [list of strings, default None]: list of PixKey IDs to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- generator of PixKey.Log objects with updated attributes
}

func Page() {
	//	Retrieve paged PixKey.Logs
	//	Receive a list of up to 100 PixKey.Log objects previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your keys.
	//
	//	Parameters (optional):
	//	- cursor [string, default None]: cursor returned on the previous page function call
	//	- ids [list of strings, default None]: Log ids to filter PixKey Logs. ex: ["5656565656565656"]
	//	- limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
	//	- after [datetime.date or string, default None]: date filter for objects created after a specified date. ex: datetime.date(2020, 3, 10)
	//	- before [datetime.date or string, default None]: date filter for objects created before a specified date. ex: datetime.date(2020, 3, 10)
	//	- types [list of strings, default None]: filter retrieved objects by types. ex: ["created", "registered", "updated", "failed", "canceling", "canceled"]
	//	- key_ids [list of strings, default None]: list of PixKey IDs to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- list of PixKey.Log objects with updated attributes
	//	- cursor to retrieve the next page of PixKey.Log objects
}
