package log

import (
	"encoding/json"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	PixKeyHolmes "github.com/starkinfra/sdk-go/starkinfra/pixkeyholmes"
	"github.com/starkinfra/sdk-go/starkinfra/utils"
	"time"
)

//	PixKeyHolmes.Log struct
//
//	Every time a PixKeyHolmes entity is updated, a corresponding PixKeyHolmes.Log
//  is generated for the entity. This log is never generated by the
//  user, but it can be retrieved to check additional information
//  on the PixKeyHolmes.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Holmes [PixKeyHolmes struct]: PixKeyHolmes entity to which the log refers to.
//	- Errors [slice of strings]: Slice of errors linked to this PixKeyHolmes event
//	- Type [string]: Type of the PixKeyHolmes event which triggered the log creation. ex: "solving", "solved"
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id      string                    `json:",omitempty"`
	Holmes  PixKeyHolmes.PixKeyHolmes `json:",omitempty"`
	Errors  []string                  `json:",omitempty"`
	Type    string                    `json:",omitempty"`
	Created *time.Time                `json:",omitempty"`
}

var resource = map[string]string{"name": "PixKeyHolmesLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific PixKeyHolmes.Log
	//
	//	Receive a single PixKeyHolmes.Log struct previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- PixKeyHolmes.Log struct that corresponds to the given id.
	var pixKeyHolmesLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &pixKeyHolmesLog)
	if unmarshalError != nil {
		return pixKeyHolmesLog, err
	}
	return pixKeyHolmesLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve PixKeyHolmes.Log structs
	//
	//	Receive a channel of PixKeyHolmes.Log structs previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//	- params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- ids [slice of strings, default nil]: Slice of ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"solving", "solved"}
	//		- holmesIds [slice of strings, default nil]: Slice of PixKeyHolmes ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- Channel of PixKeyHolmes.Log structs with updated attributes
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			var pixKeyHolmesLog Log
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &pixKeyHolmesLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- pixKeyHolmesLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logs)
		close(logsError)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged PixKeyHolmes.Log structs
	//
	//	Receive a slice of up to 100 PixKeyHolmes.Log structs previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. It must be an int between 1 and 100. ex: 50
	//		- ids [slice of strings, default nil]: Slice of ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"solving", "solved"}
	//		- holmesIds [slice of strings, default nil]: Slice of PixKeyHolmes ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- Slice of PixKeyHolmes.Log structs with updated attributes
	//	- Cursor to retrieve the next page of PixKeyHolmes.Log structs
	var pixKeyHolmesLog []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &pixKeyHolmesLog)
	if unmarshalError != nil {
		return pixKeyHolmesLog, cursor, err
	}
	return pixKeyHolmesLog, cursor, err
}
