package log

import (
	"encoding/json"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	PixChargeback "github.com/starkinfra/sdk-go/starkinfra/pixchargeback"
	"github.com/starkinfra/sdk-go/starkinfra/utils"
)

//	PixChargeback.Log struct
//
//	Every time a PixChargeback entity is modified, a corresponding PixChargeback.Log
//	is generated for the entity. This log is never generated by the user.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Chargeback [PixChargeback struct]: PixChargeback entity to which the log refers to.
//	- Type [string]: Type of the PixChargeback event which triggered the log creation. ex: "created", "failed", "delivering", "delivered", "closed", "canceled"
//	- Errors [slice of strings]: Slice of errors linked to this PixChargeback event
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id         string                      `json:",omitempty"`
	Chargeback PixChargeback.PixChargeback `json:",omitempty"`
	Type       string                      `json:",omitempty"`
	Errors     []string                    `json:",omitempty"`
	Created    string                      `json:",omitempty"`
}

var resource = map[string]string{"name": "PixChargebackLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific PixChargeback.Log
	//
	//	Receive a single PixChargeback.Log struct previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//  - id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- pixChargeback.Log struct that corresponds to the given id.
	var pixChargebackLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &pixChargebackLog)
	if unmarshalError != nil {
		return pixChargebackLog, err
	}
	return pixChargebackLog, err
}

func Query(params map[string]interface{}, user user.User) chan Log {
	//	Retrieve PixChargeback.Log structs
	//
	//	Receive a channel of PixChargeback.Log structs previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- ids [slice of strings, default nil]: Log ids to filter PixChargeback Logs. ex: []string{"5656565656565656"}
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date.  ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by types. ex: []string{"created", "failed", "delivering", "delivered", "closed", "canceled"}
	//		- chargebackIds [slice of strings, default nil]: Slice of PixChargeback IDs to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- channel of PixChargeback.Log structs with updated attributes
	var pixChargebackLog Log
	logs := make(chan Log)
	query := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &pixChargebackLog)
			if err != nil {
				print(err)
			}
			logs <- pixChargebackLog
		}
		close(logs)
	}()
	return logs
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged PixChargeback.Log structs
	//
	//	Receive a slice of up to 100 PixChargeback.Log structs previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your chargebacks.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- ids [slice of strings, default nil]: Log ids to filter PixChargeback Logs. ex: []string{"5656565656565656"}
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. Max = 100. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by types. ex: []string{"created", "failed", "delivering", "delivered", "closed", "canceled"}
	//		- chargebackIds [slice of strings, default nil]: Slice of PixChargeback IDs to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- slice of PixChargeback.Log structs with updated attributes
	//	- cursor to retrieve the next page of PixChargeback.Log structs
	var pixChargebackLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &pixChargebackLogs)
	if unmarshalError != nil {
		return pixChargebackLogs, cursor, err
	}
	return pixChargebackLogs, cursor, err
}
