package log

import (
	"encoding/json"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	CreditHolmes "github.com/starkinfra/sdk-go/starkinfra/creditholmes"
	"github.com/starkinfra/sdk-go/starkinfra/utils"
	"time"
)

//	CreditHolmes.Log struct
//
//	Every time a CreditHolmes entity is updated, a corresponding CreditHolmes.Log
//  is generated for the entity. This log is never generated by the
//  user, but it can be retrieved to check additional information
//  on the CreditHolmes.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Holmes [CreditHolmes struct]: CreditHolmes entity to which the log refers to.
//	- Errors [slice of strings]: Slice of errors linked to this CreditHolmes event
//	- Type [string]: Type of the CreditHolmes event which triggered the log creation. ex: "created", "failed", "success"
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id      string                    `json:",omitempty"`
	Holmes  CreditHolmes.CreditHolmes `json:",omitempty"`
	Errors  []string                  `json:",omitempty"`
	Type    string                    `json:",omitempty"`
	Created *time.Time                `json:",omitempty"`
}

var resource = map[string]string{"name": "CreditHolmesLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific CreditHolmes.Log
	//
	//	Receive a single CreditHolmes.Log struct previously created by the Stark Bank API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- CreditHolmes.Log struct that corresponds to the given id.
	var creditHolmesLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &creditHolmesLog)
	if unmarshalError != nil {
		return creditHolmesLog, err
	}
	return creditHolmesLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve CreditHolmes.Log structs
	//
	//	Receive a channel of CreditHolmes.Log structs previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//	- params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"canceled", "created", "expired", "failed", "refunded", "registered", "sending", "sent", "signed", "success"}
	//		- holmesIds [slice of strings, default nil]: Slice of CreditHolmes ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- Channel  of note.Log structs with updated attributes
	var creditHolmesLog Log
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &creditHolmesLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- creditHolmesLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logs)
		close(logsError)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged CreditHolmes.Log structs
	//
	//	Receive a slice of up to 100 CreditHolmes.Log structs previously created in the Stark Bank API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. It must be an int between 1 and 100. ex: 50
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"canceled", "created", "expired", "failed", "refunded", "registered", "sending", "sent", "signed", "success"}
	//		- holmesIds [slice of strings, default nil]: Slice of CreditHolmes ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- Slice of CreditHolmes.Log structs with updated attributes
	//	- Cursor to retrieve the next page of CreditHolmes.Log structs
	var creditHolmesLog []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &creditHolmesLog)
	if unmarshalError != nil {
		return creditHolmesLog, cursor, err
	}
	return creditHolmesLog, cursor, err
}
