package log

import (
	"encoding/json"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	IssuingPurchase "github.com/starkinfra/sdk-go/starkinfra/issuingpurchase"
	"github.com/starkinfra/sdk-go/starkinfra/utils"
)

//	IssuingPurchase.Log struct
//
//	Every time an IssuingPurchase entity is updated, a corresponding IssuingPurchase.Log
//	is generated for the entity. This log is never generated by the
//	user, but it can be retrieved to check additional information
//	on the IssuingPurchase.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Purchase [IssuingPurchase]: IssuingPurchase entity to which the log refers to.
//	- Installment [int]: number of the installment that is being confirmed.
//	- IssuingTransactionId [string]: Transaction ID related to the IssuingCard.
//	- Errors [slice of strings]: Slice of errors linked to this IssuingPurchase event
//	- Type [string]: Type of the IssuingPurchase event which triggered the log creation. ex: "approved", "canceled", "confirmed", "denied", "reversed", "voided".
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id                   string                          `json:",omitempty"`
	Purchase             IssuingPurchase.IssuingPurchase `json:",omitempty"`
	Installment          int                             `json:",omitempty"`
	IssuingTransactionId string                          `json:",omitempty"`
	Errors               []string                        `json:",omitempty"`
	Type                 string                          `json:",omitempty"`
	Created              string                          `json:",omitempty"`
}

var resource = map[string]string{"name": "IssuingPurchaseLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific IssuingPurchase.Log by its id
	//
	//	Receive a single IssuingPurchase.Log struct previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- issuingPurchase.Log struct that corresponds to the given id.
	var issuingPurchaseLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &issuingPurchaseLog)
	if unmarshalError != nil {
		return issuingPurchaseLog, err
	}
	return issuingPurchaseLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve IssuingPurchase.Log structs
	//
	//	Receive a channel of IssuingPurchase.Log structs previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- ids [slice of strings, default nil]: Slice of IssuingPurchase ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date.  ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"approved", "canceled", "confirmed", "denied", "reversed", "voided"}
	//		- purchaseIds [slice of strings, default nil]: Slice of Purchase ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- channel of IssuingPurchase.Log structs with updated attributes
	var issuingPurchaseLog Log
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &issuingPurchaseLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- issuingPurchaseLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logs)
		close(logsError)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged IssuingPurchase.Log structs
	//
	//	Receive a slice of up to 100 IssuingPurchase.Log structs previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- ids [slice of strings, default nil]: Slice of IssuingPurchase ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. Max = 100. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date.  ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"approved", "canceled", "confirmed", "denied", "reversed", "voided"}
	//		- purchaseIds [slice of strings, default nil]: Slice of Purchase ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- slice of IssuingPurchase.Log structs with updated attributes
	//	- cursor to retrieve the next page of IssuingPurchase.Log structs
	var issuingPurchaseLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &issuingPurchaseLogs)
	if unmarshalError != nil {
		return issuingPurchaseLogs, cursor, err
	}
	return issuingPurchaseLogs, cursor, err
}
