package log

import (
	"encoding/json"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	PixRequest "github.com/starkinfra/sdk-go/starkinfra/pixrequest"
	"github.com/starkinfra/sdk-go/starkinfra/utils"
	"time"
)

//	PixRequest.Log struct
//
//	Every time a PixRequest entity is modified, a corresponding PixRequest.Log
//	is generated for the entity. This log is never generated by the user.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Request [PixRequest struct]: PixRequest entity to which the log refers to.
//	- Type [string]: Type of the PixRequest event which triggered the log creation. ex: "sent", "denied", "failed", "created", "success", "approved", "credited", "refunded", "processing"
//	- Errors [slice of strings]: Slice of errors linked to this PixRequest event
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id      string                `json:",omitempty"`
	Request PixRequest.PixRequest `json:",omitempty"`
	Type    string                `json:",omitempty"`
	Errors  interface{}           `json:",omitempty"`
	Created *time.Time            `json:",omitempty"`
}

var resource = map[string]string{"name": "PixRequestLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific PixRequest.Log by its id
	//
	//	Receive a single PixRequest.Log struct previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- pixRequest.Log struct that corresponds to the given id.
	var pixRequestLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &pixRequestLog)
	if unmarshalError != nil {
		return pixRequestLog, err
	}
	return pixRequestLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve PixRequest.Log structs
	//
	//	Receive a channel of PixRequest.Log structs previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by types. Options: ["sent", "denied", "failed", "created", "success", "approved", "credited", "refunded", "processing"}
	//		- requestIds [slice of strings, default nil]: Slice of PixRequest ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- reconciliationId [string, default nil]: PixRequest reconciliation id to filter retrieved structs. ex: "b77f5236-7ab9-4487-9f95-66ee6eaf1781"
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- channel of PixRequest.Log structs with updated attributes
	var pixRequestLog Log
	logs := make(chan Log)
	logsErrors := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &pixRequestLog)
			if err != nil {
				logsErrors <- Error.UnknownError(err.Error())
				continue
			}
			logs <- pixRequestLog
		}
		for err := range errorChannel {
			logsErrors <- err
		}
		close(logs)
		close(logsErrors)
	}()
	return logs, logsErrors
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged PixRequest.Log structs
	//
	//	Receive a slice of up to 100 PixRequest.Log structs previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. Max = 100. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by types. Options: ["sent", "denied", "failed", "created", "success", "approved", "credited", "refunded", "processing"}
	//		- requestIds [slice of strings, default nil]: Slice of PixRequest IDs to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- reconciliationId [string]: PixRequest reconciliation id to filter retrieved structs. ex: "b77f5236-7ab9-4487-9f95-66ee6eaf1781"
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- slice of PixRequest.Log structs with updated attributes
	//	- cursor to retrieve the next page of PixRequest.Log structs
	var pixRequestLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &pixRequestLogs)
	if unmarshalError != nil {
		return pixRequestLogs, cursor, err
	}
	return pixRequestLogs, cursor, err
}
