package issuingbalance

//	IssuingBalance object
//
//	The IssuingBalance object displays the current issuing balance of the Workspace,
//	which is the result of the sum of all transactions within this
//	Workspace. The balance is never generated by the user, but it
//	can be retrieved to see the available information.
//
//	Attributes (return-only):
//	- id [string]: unique id returned when IssuingBalance is created. ex: "5656565656565656"
//	- amount [integer]: current balance amount of the Workspace in cents. ex: 200 (= R$ 2.00)
//	- currency [string]: currency of the current Workspace. Expect others to be added eventually. ex: "BRL"
//	- updated [string]: latest update datetime for the IssuingBalance. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)

type IssuingBalance struct {
	Id       string
	Amount   int
	Currency string
	Updated  string
}

var resource = map[string]string{"class": IssuingBalance{}, "name": "IssuingBalance"}

func Get() {
	//	Retrieve the IssuingBalance object
	//	Receive the IssuingBalance object linked to your Workspace in the Stark Infra API
	//
	//	Parameters (optional):
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- IssuingBalance object with updated attributes

}
