package log

//	issuing_invoice.Log object
//	Every time an IssuingInvoice entity is updated, a corresponding issuing_invoice.Log
//	is generated for the entity. This log is never generated by the
//	user, but it can be retrieved to check additional information
//	on the IssuingInvoice.
//
//	Attributes:
//	- id [string]: unique id returned when the log is created. ex: "5656565656565656"
//	- invoice [IssuingInvoice]: IssuingInvoice entity to which the log refers to.
//	- type [string]: type of the IssuingInvoice event which triggered the log creation. ex: "created", "credited", "expired", "overdue", "paid".
//	- created [datetime.datetime]: creation datetime for the log. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)

type Log struct {
	Id      string
	Invoice IssuingInvoice
	Type    string
	Created string
}

var resource = map[string]string{"class": IssuingInvoiceLog{}, "name": "IssuingInvoiceLog"}

func Get() {
	//	Retrieve a specific issuing_invoice.Log
	//	Receive a single issuing_invoice.Log object previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: object unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- issuing_invoice.Log object with updated attributes
}

func Query() {
	//	Retrieve issuing_invoice.Log
	//	Receive a generator of issuing_invoice.Log objects previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//	- ids [list of strings, default None]: list of IssuingInvoice ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
	//	- limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
	//	- after [datetime.date or string, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
	//	- before [datetime.date or string, default None] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
	//	- types [list of strings, default None]: filter for log event types. ex: ["created", "credited", "expired", "overdue", "paid"]
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- generator of issuing_invoice.Log objects with updated attributes

}

func Page() {
	//	Retrieve paged issuing_invoice.Log
	//	Receive a list of up to 100 issuing_invoice.Log objects previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//	- cursor [string, default None]: cursor returned on the previous page function call
	//	- ids [list of strings, default None]: list of IssuingInvoice ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
	//	- limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
	//	- after [datetime.date or string, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
	//	- before [datetime.date or string, default None] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
	//	- types [list of strings, default None]: filter for log event types. ex: ["created", "credited", "expired", "overdue", "paid"]
	//	- user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
	//
	//	Return:
	//	- list of issuing_invoice.Log objects with updated attributes
	//	- cursor to retrieve the next page of issuing_invoice.Log objects
}
