package log

import (
	"encoding/json"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	BusinessAccountRequest "github.com/starkinfra/sdk-go/starkinfra/businessaccountrequest"
	"github.com/starkinfra/sdk-go/starkinfra/utils"
	"time"
)

//	BusinessAccountRequest.Log struct
//
//	Every time a BusinessAccountRequest entity is modified, a corresponding BusinessAccountRequest.Log
//	is generated for the entity. This log is never generated by the
//	user, but it can be retrieved to check additional information
//	on the BusinessAccountRequest.
//
//	Attributes (return-only):
//	- Id [string]: unique id returned when the log is created. ex: "5656565656565656"
//	- Request [BusinessAccountRequest]: BusinessAccountRequest entity to which the log refers to.
//	- Errors [slice of strings]: slice of errors linked to this BusinessAccountRequest event
//	- Type [string]: type of the BusinessAccountRequest event which triggered the log creation. ex: "created", "processing", "approved", "denied", "failed"
//	- Created [time.Time]: creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id      string                                        `json:",omitempty"`
	Request BusinessAccountRequest.BusinessAccountRequest `json:",omitempty"`
	Errors  []string                                      `json:",omitempty"`
	Type    string                                        `json:",omitempty"`
	Created *time.Time                                    `json:",omitempty"`
}

var resource = map[string]string{"name": "BusinessAccountRequestLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific BusinessAccountRequest.Log
	//
	//	Receive a single BusinessAccountRequest.Log struct previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- BusinessAccountRequest.Log struct that corresponds to the given id.
	var businessAccountRequestLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &businessAccountRequestLog)
	if unmarshalError != nil {
		return businessAccountRequestLog, err
	}
	return businessAccountRequestLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve BusinessAccountRequest.Logs
	//
	//	Receive a channel of BusinessAccountRequest.Log structs previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: filter for log event types. ex: []string{"created", "processing", "approved", "denied", "failed"}
	//		- accountRequestIds [slice of strings, default nil]: slice of BusinessAccountRequest ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- channel of BusinessAccountRequest.Log structs with updated attributes
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			var businessAccountRequestLog Log
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &businessAccountRequestLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- businessAccountRequestLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logs)
		close(logsError)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged BusinessAccountRequest.Logs
	//
	//	Receive a slice of up to 100 BusinessAccountRequest.Log structs previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: cursor returned on the previous page function call
	//		- limit [int, default 100]: maximum number of structs to be retrieved. It must be an integer between 1 and 100. ex: 50
	//		- after [string, default nil]: date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: filter for log event types. ex: []string{"created", "processing", "approved", "denied", "failed"}
	//		- accountRequestIds [slice of strings, default nil]: slice of BusinessAccountRequest ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- slice of BusinessAccountRequest.Log structs with updated attributes
	//	- cursor to retrieve the next page of BusinessAccountRequest.Log structs
	var businessAccountRequestLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &businessAccountRequestLogs)
	if unmarshalError != nil {
		return businessAccountRequestLogs, cursor, err
	}
	return businessAccountRequestLogs, cursor, err
}
