package log

import (
	"encoding/json"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	PixPullRequest "github.com/starkinfra/sdk-go/starkinfra/pixpullrequest"
	"github.com/starkinfra/sdk-go/starkinfra/utils"
	"time"
)

//	PixPullRequest.Log struct
//
//	Every time a PixPullRequest entity is modified, a corresponding PixPullRequest.Log
//	is generated for the entity. This log is never generated by the user.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Request [PixPullRequest struct]: PixPullRequest entity to which the log refers to.
//	- Type [string]: Type of the PixRequest event which triggered the log creation. ex: "sent", "denied", "failed", "created", "success", "approved", "credited", "refunded", "processing"
//	- Errors [slice of strings]: Slice of errors linked to this PixRequest event
//	- Description [string]: Description of the log event. ex: "The Pix Pull Request was settled."
//  - Reason [string]: Reason for the log event. ex: "The Pix Pull Request was settled."
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id          string                        `json:",omitempty"`
	Request     PixPullRequest.PixPullRequest `json:",omitempty"`
	Type        string                        `json:",omitempty"`
	Errors      interface{}                   `json:",omitempty"`
	Description string                        `json:",omitempty"`
	Reason      string                        `json:",omitempty"`
	Created     *time.Time                    `json:",omitempty"`
}

var resource = map[string]string{"name": "PixPullRequestLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific PixPullRequest.Log by its id
	//
	//	Receive a single PixPullRequest.Log struct previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- pixPullRequest.Log struct that corresponds to the given id.
	var pixPullRequestLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &pixPullRequestLog)
	if unmarshalError != nil {
		return pixPullRequestLog, err
	}
	return pixPullRequestLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve PixPullRequest.Log structs
	//
	//	Receive a channel of PixPullRequest.Log structs previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by types. Options: ["sent", "denied", "failed", "created", "success", "approved", "credited", "refunded", "processing"}
	//		- requestIds [slice of strings, default nil]: Slice of PixPullRequest ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- channel of PixPullRequest.Log structs with updated attributes
	var pixPullRequestLog Log
	logs := make(chan Log)
	logsErrors := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &pixPullRequestLog)
			if err != nil {
				logsErrors <- Error.UnknownError(err.Error())
				continue
			}
			logs <- pixPullRequestLog
		}
		for err := range errorChannel {
			logsErrors <- err
		}
		close(logs)
		close(logsErrors)
	}()
	return logs, logsErrors
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged PixPullRequest.Log structs
	//
	//	Receive a slice of up to 100 PixPullRequest.Log structs previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. Max = 100. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by types. Options: ["sent", "denied", "failed", "created", "success", "approved", "credited", "refunded", "processing"}
	//		- requestIds [slice of strings, default nil]: Slice of PixPullRequest IDs to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- slice of PixPullRequest.Log structs with updated attributes
	//	- cursor to retrieve the next page of PixPullRequest.Log structs
	var pixPullRequestLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &pixPullRequestLogs)
	if unmarshalError != nil {
		return pixPullRequestLogs, cursor, err
	}
	return pixPullRequestLogs, cursor, err
}
