package log

import (
	"encoding/json"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	BusinessAttachment "github.com/starkinfra/sdk-go/starkinfra/businessattachment"
	"github.com/starkinfra/sdk-go/starkinfra/utils"
	"time"
)

//	BusinessAttachment.Log struct
//
//	Every time a BusinessAttachment entity is updated, a corresponding BusinessAttachment.Log
//	is generated for the entity. This log is never generated by the
//	user, but it can be retrieved to check additional information
//	on the BusinessAttachment.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Attachment [BusinessAttachment struct]: BusinessAttachment entity to which the log refers to.
//	- Errors [slice of strings]: Slice of errors linked to this BusinessAttachment event
//	- Type [string]: Type of the BusinessAttachment event which triggered the log creation. ex: "created", "canceled", "approved", "denied"
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id         string                                `json:",omitempty"`
	Attachment BusinessAttachment.BusinessAttachment `json:",omitempty"`
	Errors     []string                              `json:",omitempty"`
	Type       string                                `json:",omitempty"`
	Created    *time.Time                            `json:",omitempty"`
}

var resource = map[string]string{"name": "BusinessAttachmentLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific BusinessAttachment.Log
	//
	//	Receive a single BusinessAttachment.Log struct previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- businessAttachment.Log struct that corresponds to the given id.
	var businessAttachmentLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &businessAttachmentLog)
	if unmarshalError != nil {
		return businessAttachmentLog, err
	}
	return businessAttachmentLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve BusinessAttachment.Log
	//
	//	Receive a channel of BusinessAttachment.Log structs previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- ids [slice of strings, default nil]: Slice of ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date.  ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"created", "canceled", "approved", "denied"}
	//		- attachmentIds [slice of strings, default nil]: list of BusinessAttachment ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- channel of BusinessAttachment.Log structs with updated attributes
	var businessAttachmentLog Log
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &businessAttachmentLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- businessAttachmentLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logs)
		close(logsError)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged BusinessAttachment.Log
	//
	//	Receive a slice of up to 100 BusinessAttachment.Log structs previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- ids [slice of strings, default nil]: Slice of ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. Max = 100. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date.  ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"created", "canceled", "approved", "denied"}
	//		- attachmentIds [slice of strings, default nil]: list of BusinessAttachment ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- slice of BusinessAttachment.Log structs with updated attributes
	//	- cursor to retrieve the next page of BusinessAttachment.Log structs
	var businessAttachmentLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &businessAttachmentLogs)
	if unmarshalError != nil {
		return businessAttachmentLogs, cursor, err
	}
	return businessAttachmentLogs, cursor, err
}
