package log

import (
	"encoding/json"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	PixDispute "github.com/starkinfra/sdk-go/starkinfra/pixdispute"
	"github.com/starkinfra/sdk-go/starkinfra/utils"
	"time"
)

//	PixDispute.Log struct
//
//	Every time a PixDispute entity is modified, a corresponding PixDispute.Log
//	is generated for the entity. This log is never generated by the user.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Dispute [PixDispute struct]: PixDispute entity to which the log refers to.
//	- Type [string]: Type of the PixDispute event which triggered the log creation. ex: "analysed", "canceled", "canceling", "closed", "created", "delivered", "delivering", "failed", "reversing"
//	- Errors [slice of strings]: Slice of errors linked to this PixDispute event
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id      string                `json:",omitempty"`
	Dispute PixDispute.PixDispute `json:",omitempty"`
	Type    string                `json:",omitempty"`
	Errors  []string              `json:",omitempty"`
	Created *time.Time            `json:",omitempty"`
}

var resource = map[string]string{"name": "PixDisputeLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific PixDispute.Log by its id
	//
	//	Receive a single PixDispute.Log struct previously created by the Stark Infra API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- pixDispute.Log struct that corresponds to the given id.
	var pixDisputeLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &pixDisputeLog)
	if unmarshalError != nil {
		return pixDisputeLog, err
	}
	return pixDisputeLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve PixDispute.Log structs
	//
	//	Receive a channel of PixDispute.Log structs previously created in the Stark Infra API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by types. ex: []string{"created", "delivered", "analysed"}
	//		- disputeIds [slice of strings, default nil]: Slice of PixDispute ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- ids [slice of strings, default nil]: Slice of Log ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- channel of PixDispute.Log structs with updated attributes
	var pixDisputeLog Log
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &pixDisputeLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- pixDisputeLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logs)
		close(logsError)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged PixDispute.Log structs
	//
	//	Receive a slice of up to 100 PixDispute.Log structs previously created in the Stark Infra API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. Max = 100. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by types. ex: []string{"created", "delivered", "analysed"}
	//		- disputeIds [slice of strings, default nil]: Slice of PixDispute ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- ids [slice of strings, default nil]: Slice of Log ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.User was set before function call
	//
	//	Return:
	//	- slice of PixDispute.Log structs with updated attributes
	//	- cursor to retrieve the next page of PixDispute.Log structs
	var pixDisputeLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &pixDisputeLogs)
	if unmarshalError != nil {
		return pixDisputeLogs, cursor, err
	}
	return pixDisputeLogs, cursor, err
}
